spring.application.name=agri-erp

# Server Port
server.port=8080

# MySQL Database Connection (Added agri_erp to the URL)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/agri_erp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=toodamnhot

# Hibernate JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect